export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";

export const ALLCOURSE_CATEGORY_REQUEST = "ALLCOURSE_CATEGORY_REQUEST";
export const ALLCOURSE_CATEGORY_SUCCESS = "ALLCOURSE_CATEGORY_SUCCESS";
export const ALLCOURSE_CATEGORY_FAIL = "ALLCOURSE_CATEGORY_FAIL";

export const DELETECOURSE_CATEGORY_REQUEST = "DELETECOURSE_CATEGORY_REQUEST";
export const DELETECOURSE_CATEGORY_SUCCESS = "DELETECOURSE_CATEGORY_SUCCESS";
export const DELETECOURSE_CATEGORY_FAIL = "DELETECOURSE_CATEGORY_FAIL";

export const SVCOURSE_CATEGORY_REQUEST = "SVCOURSE_CATEGORY_REQUEST";
export const SVCOURSE_CATEGORY_SUCCESS = "SVCOURSE_CATEGORY_SUCCESS";
export const SVCOURSE_CATEGORY_FAIL = "SVCOURSE_CATEGORY_FAIL";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";